const COLORS={"JNTO":"#65b96f","観光庁":"#2e83c3","Travel Voice":"#ff775c","やまとごころ.jp":"#a77be8","時事ドットコム":"#4c8fe8","訪日ラボ":"#e7ad32"};
let all=[],active="すべて";
const $=s=>document.querySelector(s),esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const date=s=>{if(!s)return "日付不明";const d=new Date(s);return isNaN(d)?s:new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"short",day:"numeric"}).format(d)};
function groups(rows){const m=new Map();rows.forEach(x=>{const k=x.topic_group||x.url;if(!m.has(k))m.set(k,[]);m.get(k).push(x)});return [...m.values()]}
function renderFeatured(){const picks=all.filter(x=>x.image_url).sort((a,b)=>new Date(b.published||0)-new Date(a.published||0)).filter((x,i,a)=>a.findIndex(y=>(y.topic_group||y.url)===(x.topic_group||x.url))===i).slice(0,3);$("#featured-wrap").hidden=!picks.length;$("#featured").innerHTML=picks.map(x=>`<a class="feature" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer"><img src="${esc(x.image_url)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.style.display='none'"><div class="feature-copy"><span class="category">${esc(x.category||"その他")}</span><h3>${esc(x.title)}</h3><div class="feature-meta">${esc(x.source)} ・ ${esc(date(x.published))} ↗</div></div></a>`).join("")}
function render(){const q=$("#search").value.trim().toLowerCase(),sort=$("#sort").value,cat=$("#category").value;let rows=all.filter(x=>(active==="すべて"||x.source===active)&&(cat==="すべて"||x.category===cat)&&(!q||`${x.title} ${x.summary} ${x.source} ${x.category}`.toLowerCase().includes(q)));rows.sort(sort==="source"?(a,b)=>a.source.localeCompare(b.source,"ja"):(a,b)=>new Date(b.published||0)-new Date(a.published||0));const gs=groups(rows);$("#result-count").textContent=`${rows.length}件・${gs.length}トピック`;$("#articles").innerHTML=gs.length?gs.map(g=>{const x=g[0],related=g.slice(1);return `<article class="card" style="--accent:${COLORS[x.source]||"#999"}"><div class="meta"><span class="source-badge">${esc(x.source)}</span><time>${esc(date(x.published))}</time></div><h3>${esc(x.title)}</h3><span class="category">${esc(x.category||"その他")}</span>${x.summary?`<p>${esc(x.summary)}</p>`:""}<a class="read" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">元記事を読む ↗</a>${related.length?`<details class="related"><summary>関連する${related.length}記事</summary>${related.map(r=>`<a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.source)}｜${esc(r.title)} ↗</a>`).join("")}</details>`:""}</article>`}).join(""):`<div class="empty">該当するトピックがありません。</div>`}
function buildFilters(){const names=["すべて",...new Set(all.map(x=>x.source))];$("#filters").innerHTML=names.map(x=>`<button class="filter ${x===active?"active":""}" data-source="${esc(x)}">${esc(x)}</button>`).join("");document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{active=b.dataset.source;buildFilters();render()});const cats=["すべて",...new Set(all.map(x=>x.category||"その他"))];$("#category").innerHTML=cats.map(x=>`<option value="${esc(x)}">${x==="すべて"?"すべてのカテゴリー":esc(x)}</option>`).join("")}
fetch(`data/topics.json?v=${Date.now()}`).then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{all=data.articles||[];$("#updated").textContent=date(data.updated_at);$("#count").textContent=`${all.length} articles`;buildFilters();renderFeatured();render();$("#source-list").innerHTML=(data.sources||[]).map(s=>`<a class="source-item" href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.name)}<small>${all.filter(x=>x.source===s.name).length} topics ↗</small></a>`).join("")}).catch(()=>{$("#articles").innerHTML='<div class="empty">データを取得できませんでした。しばらくしてから再読み込みしてください。</div>'});
$("#search").addEventListener("input",render);$("#sort").addEventListener("change",render);$("#category").addEventListener("change",render);
